export enum ROUTES {
  MAIN_SCREEN = 'MAIN_SCREEN',
  START_SCREEN = 'START_SCREEN',
  SEARCH_SCREEN = 'SEARCH_SCREEN',
  DOWNLOAD_SCREEN = 'DOWNLOAD_SCREEN',
  DOWNLOAD_STACK_SCREEN = 'DOWNLOAD_STACK_SCREEN',
  FULL_VIDEO_SCREEN = 'FULL_VIDEO_SCREEN',
  PERSONAL_INFO = 'PERSONAL_INFO',
  MAIN_STACK_SCREEN = 'MAIN_STACK_SCREEN',
}
