import LocalizedStrings from 'react-native-localization';
import {
  A_DESCRIBE,
  A_TYPE,
  ABOUT,
  ABOUT_PROJECT,
  AGREEMENT_TO_OUR_LEGAL_TERMS,
  All_OTHER,
  ALL_PERSONAL_INFO,
  ALL_USERS,
  ANY_BREACH,
  ANY_DISPUTE,
  ANY_FORMAT,
  AS_A_USER_OF_SERVICES,
  B_DESCRIBE,
  B_TYPE,
  BASED_ON_THE_APP_LAW,
  BENEFITS,
  BINDING_ARBITRATION,
  BU_DIRECTLY,
  BU_SENDING,
  BU_USING_SERVICES,
  BUSINESS_TRANSFERS,
  BY_SUBMITTING,
  C_DESCRIBE,
  C_TYPE,
  CALIFORNIA_CIVIL,
  CALIFORNIA_RESIDENT,
  CCPA,
  CONFIDENTIALITY,
  CONSENT,
  CONSUMER_MEANS,
  CONTACT_US,
  CONTACTS,
  COOKIES_AND_SIMILAR,
  COPY_LINK,
  D_DESCRIBE,
  D_TYPE,
  DEPENDING_ON_THE_CIRCUMSTANCES,
  DEPENDING_ON_WHERE_YOU,
  DO_WE_PROCESS,
  DO_WE_PROCESS_SENSITIVE_INFO,
  DO_WE_RECEIVE,
  DO_YOU_WANT_TO_SAVE_MUSIC,
  DO_YOU_WANT_TO_SAVE_VIDEO,
  DOWNLOAD,
  DOWNLOAD_MP3,
  DOWNLOAD_VIDEO,
  DOWNLOADS,
  E_DESCRIBE,
  E_TYPE,
  EIGHTEENTH_PART_OF_TERMS,
  EIGHTH_PART,
  EIGHTH_PART_OF_TERMS,
  ELEVENTH_PART,
  ELEVENTH_PART_OF_TERMS,
  EMAIL,
  ENGAGE_WITH_US,
  ENTER_YOUR_LINK,
  EVERY_INDIVIDUAL,
  EVERY_INDIVIDUAL_STATE,
  EXCEPT_AND_SET_OUT,
  EXERCISE_YOUR_RIGHTS,
  F_DESCRIBE,
  F_TYPE,
  FIFTEENTH_PART,
  FIFTEENTH_PART_OF_TERMS,
  FIFTH_PART,
  FIFTH_PART_OF_TERMS,
  FIRST_PART,
  FIRST_PART_OF_TERMS,
  FLIPTOK_BOTTOM_TEXT,
  FLIPTOK_HAS_NOT_DISCLOSED,
  FOURTEENTH_PART,
  FOURTEENTH_PART_OF_TERMS,
  FOURTH_PART,
  FOURTH_PART_OF_TERMS,
  G_DESCRIBE,
  G_TYPE,
  GO_TO_THE_APP,
  H_DESCRIBE,
  H_TYPE,
  HIGH_QUALITY,
  HOW_DO_WE_PROCESS_INFO,
  HOW_DO_WE_USE,
  HOW_TO_USE,
  HOW_WE_KEEP_INFO,
  HOWEVER_PLEASE,
  I_DESCRIBE,
  I_TYPE,
  IF_ANY_COMPLAINT,
  IF_THIS_DEFINITION,
  IF_THIS_DEFINITIONS,
  IF_WE_DECLINE,
  IF_WE_TERMINATE,
  IF_YOU_ADULT,
  IF_YOU_CHOSEN,
  IF_YOU_HAVE_QUESTION,
  IF_YOU_HAVE_QUESTIONS,
  IF_YOU_LOCATED_EU,
  IF_YOU_LOCATED_IN_CANADA,
  IF_YOU_NEED,
  IF_YOU_PROVIDE,
  IF_YOU_RESIDENT_OF_CALIFORNIA,
  IF_YOU_RESIDENT_OF_VIRGINIA,
  IF_YOU_USE_AGENT,
  IF_YOU_USING,
  IF_YOU_WISH,
  IN_NO_EVENT,
  IN_ORDER_TO_RESOLVE,
  IN_SHORT,
  IN_SOME_EXCEPTIONAL_CASES,
  IN_SOME_REGIONS,
  IN_SOME_REGIONS_EEA_UK,
  IN_WHAT_SITUATIONS,
  INFORMAL_NEGOTIATIONS,
  INFORMATION,
  J_DESCRIBE,
  J_TYPE,
  K_DESCRIBE,
  K_TYPE,
  L_TYPE,
  LAST_UPDATE,
  LEGAL_OBLIGATIONS,
  MORE_INFO,
  MORE_INFO_ABOUT,
  MOST_WEB,
  MOST_WEB_AND_MOBILE,
  MUSIC_SAVED,
  NINETEENTH_PART_OF_TERMS,
  NINTH_PART,
  NINTH_PART_OF_TERMS,
  NO_INTERNET,
  NO_USER_FEES,
  OKAY,
  OOPS,
  OPEN_THE_APP,
  OTHER_PRIVACY_RIGHTS,
  OUR_CONTENT,
  OUR_INTELLECTUAL_PROPERTY,
  PERSONAL_DATA_MEANS,
  PERSONAL_INFO,
  PERSONAL_INFO_YOU_DISCLOSE,
  PLEASE_REVIEW,
  PRIVACY_POLICY,
  QUESTION_OR_CONCERNS,
  READING_THIS_NOTICE,
  RIGHT_TO_APPEAL,
  RIGHT_TO_BE_INFORMED,
  RIGHT_TO_BE_INFORMED_WHETHER_OR_NOT,
  RIGHT_TO_NON_DISCRIMINATION,
  RIGHTS_TO_LIMIT,
  RIGHTS_TO_REQUEST,
  SALE_OF_PERSONAL_DATA,
  SEARCH,
  SECOND_PART,
  SECOND_PART_OF_TERMS,
  SENSITIVE_INFO,
  SEVENTEENTH_PART_OF_TERMS,
  SEVENTH_PART,
  SEVENTH_PART_OF_TERMS,
  SIXTEENTH_PART_OF_TERMS,
  SIXTH_PART,
  SIXTH_PART_OF_TERMS,
  SORRY,
  SUBJECT_TO_YOUR_COMPLIANCE,
  SUBMISSION,
  SUMMARY_OF_KEY_POINTS,
  SUMMARY_PROVIDES,
  SUPPLEMENTAL,
  TABLE_OF_CONTENTS,
  TENTH_PART,
  TENTH_PART_OF_TERMS,
  TERMS_AND_CONDITIONS,
  THE_CONTENT_AND_MARKS,
  THE_FINAL_STEP,
  THE_GENERAL_DATA_PROTECTION,
  THE_INFO_PROVIDED,
  THE_INFO_WE_COLLECT,
  THE_SERVICES,
  THE_SERVICES_ARE_PROVIDED,
  THE_SERVICES_DOES_NOT,
  THERE_MAY_BE_INFORMATION,
  THESE_LEGAL_TERMS,
  THESE_LEGAL_TERMS_AND_ANY_POLICIES,
  THESE_LEGAL_TERMS_GOVERNED,
  THESE_LEGAL_TERMS_SHALL,
  THIRD_PART,
  THIRD_PART_OF_TERMS,
  THIRTEENTH_PART,
  THIRTEENTH_PART_OF_TERMS,
  THIS_PRIVACY_NOTICE,
  TO_EXPEDITE_RESOLUTION,
  TO_MAY_PROCESS,
  TO_SAVE_OR_PROTECT,
  TOU_MAY_NOT_ACCESS,
  TWELFTH_PART,
  TWELFTH_PART_OF_TERMS,
  TWENTIETH_ONE_PART_OF_TERMS,
  TWENTIETH_PART_OF_TERMS,
  TWENTIETH_TWO_PART_OF_TERMS,
  UNDER_THE_VIRGINIA,
  UPON_RECEIVING,
  UPON_RECEIVING_YOUR_REQUEST,
  USING_THE_FLIPTOK,
  VERIFICATION_PROCESS,
  VIDEO_SAVED,
  VIRGINIA_CDPA,
  VISIT_OUR_WEBSITE,
  VISITING_THE_SERVICES,
  VITAL_INTERESTS,
  WANT_TO_LEARN_MORE,
  WE_AIM_TO_PROTECT,
  WE_ALLOW_ADVERTISERS,
  WE_ARE_FLIPTOK,
  WE_ARE_THE_OWNER,
  WE_CANNOT_GUARANTEE,
  WE_CARE_ABOUT,
  WE_COLLECT,
  WE_DO_NOT_ASSERT,
  WE_DO_NOT_KNOWINGLY,
  WE_DO_NOT_PROCESS,
  WE_DO_NOT_PROCESS_SENSITIVE,
  WE_DO_NOT_RECEIVE,
  WE_HAVE_IMPLEMENTED,
  WE_HAVE_NOT_COLLECTED,
  WE_HAVE_ORGANIZATIONAL,
  WE_KEEP_YOUR_INFO,
  WE_MAY_ALSO,
  WE_MAY_DISCLOSE,
  WE_MAY_NEED,
  WE_MAY_PROCESS_INFO_FOR_SPECIFIC_PERMISSION,
  WE_MAY_PROCESS_INFO_TO_PROTECT,
  WE_MAY_PROCESS_YOUR_INFO,
  WE_MAY_PROCESS_YOUR_INFO_FOR_COMPLIANCE,
  WE_MAY_REQUEST,
  WE_MAY_SHARE_INFO,
  WE_MAY_SHARE_INFO_IN_SPECIFIC_SITUATIONS,
  WE_MAY_SHARE_OR_TRANSFER_INFO,
  WE_MAY_UPDATE_INFO,
  WE_MAY_USE_COOKIES,
  WE_MAY_USE_YOUR_PERSONAL_INFO,
  WE_NOT_DISCRIMINATE,
  WE_ONLY_PROCESS,
  WE_ONLY_USE_PERSONAL_INFO,
  WE_OPERATE,
  WE_PROCESS_YOUR_INFO,
  WE_PROCESS_YOUR_INFO_TO_PROVIDE,
  WE_PROCESS_YOUR_PERSONAL_INFO,
  WE_RECOMMEND,
  WE_RESERVE_ALL,
  WE_RESERVE_RIGHT,
  WE_RESERVE_THE_RIGHT,
  WE_VALUE_YOUR_ATTENTION,
  WE_WILL_CONSIDER,
  WE_WILL_MAINTAIN,
  WE_WILL_ONLY_KEEP,
  WE_WILL_UPDATE,
  WHAT_ARE_YOU_RIGHTS,
  WHAT_CATEGORIES,
  WHEN_WE_HAVE_NO,
  WHEN_YOU_VISIT,
  WILL_YOUR_MORE_INFO,
  WITHDRAWING_YOUR_CONSENT,
  WITHDRAWING_YOUR_CONSENT_IF_WE,
  WORKING_WITH,
  YOU_AGREE_TO_DEFEND,
  YOU_AND_SERVICES,
  YOU_ARE_RESPONSIBLE,
  YOU_CAN_ASK,
  YOU_CAN_CONTACT,
  YOU_CAN_CONTACT_US,
  YOU_MAY_CONTACT,
  YOU_MAY_CONTACT_US,
  YOU_MAY_OBJECT,
  YOUR_RIGHTS,
  YOUR_RIGHTS_WITH_RESPECT,
  YOUR_SUBMISSION,
  YOUR_USE_OF_OUR_SERVICES,
} from './englishText';
import {
  A_DESCRIBE_RU,
  A_TYPE_RU,
  ABOUT_PROJECT_RU,
  ABOUT_RU,
  AGREEMENT_TO_OUR_LEGAL_TERMS_RU,
  All_OTHER_RU,
  ALL_PERSONAL_INFO_RU,
  ALL_USERS_RU,
  ANY_BREACH_RU,
  ANY_DISPUTE_RU,
  ANY_FORMAT_RU,
  AS_A_USER_OF_SERVICES_RU,
  B_DESCRIBE_RU,
  B_TYPE_RU,
  BASED_ON_THE_APP_LAW_RU,
  BENEFITS_RU,
  BINDING_ARBITRATION_RU,
  BU_DIRECTLY_RU,
  BU_SENDING_RU,
  BU_USING_SERVICES_RU,
  BUSINESS_TRANSFERS_RU,
  BY_SUBMITTING_RU,
  C_DESCRIBE_RU,
  C_TYPE_RU,
  CALIFORNIA_CIVIL_RU,
  CALIFORNIA_RESIDENT_RU,
  CCPA_RU,
  CONFIDENTIALITY_RU,
  CONSENT_RU,
  CONSUMER_MEANS_RU,
  CONTACT_US_RU,
  CONTACTS_RU,
  COOKIES_AND_SIMILAR_RU,
  COPY_LINK_RU,
  D_DESCRIBE_RU,
  D_TYPE_RU,
  DEPENDING_ON_THE_CIRCUMSTANCES_RU,
  DEPENDING_ON_WHERE_YOU_RU,
  DO_WE_PROCESS_RU,
  DO_WE_PROCESS_SENSITIVE_INFO_RU,
  DO_WE_RECEIVE_RU,
  DO_YOU_WANT_TO_SAVE_MUSIC_RU,
  DO_YOU_WANT_TO_SAVE_VIDEO_RU,
  DOWNLOAD_MP3_RU,
  DOWNLOAD_RU,
  DOWNLOAD_VIDEO_RU,
  DOWNLOADS_RU,
  E_DESCRIBE_RU,
  E_TYPE_RU,
  EIGHTEENTH_PART_OF_TERMS_RU,
  EIGHTH_PART_OF_TERMS_RU,
  EIGHTH_PART_RU,
  ELEVENTH_PART_OF_TERMS_RU,
  ELEVENTH_PART_RU,
  ENGAGE_WITH_US_RU,
  ENTER_YOUR_LINK_RU,
  EVERY_INDIVIDUAL_RU,
  EVERY_INDIVIDUAL_STATE_RU,
  EXCEPT_AND_SET_OUT_RU,
  EXERCISE_YOUR_RIGHTS_RU,
  F_DESCRIBE_RU,
  F_TYPE_RU,
  FIFTEENTH_PART_OF_TERMS_RU,
  FIFTEENTH_PART_RU,
  FIFTH_PART_OF_TERMS_RU,
  FIFTH_PART_RU,
  FIRST_PART_OF_TERMS_RU,
  FIRST_PART_RU,
  FLIPTOK_HAS_NOT_DISCLOSED_RU,
  FOURTEENTH_PART_OF_TERMS_RU,
  FOURTEENTH_PART_RU,
  FOURTH_PART_OF_TERMS_RU,
  FOURTH_PART_RU,
  G_DESCRIBE_RU,
  G_TYPE_RU,
  GO_TO_THE_APP_RU,
  H_DESCRIBE_RU,
  H_TYPE_RU,
  HIGH_QUALITY_RU,
  HOW_DO_WE_PROCESS_INFO_RU,
  HOW_DO_WE_USE_RU,
  HOW_TO_USE_RU,
  HOW_WE_KEEP_INFO_RU,
  HOWEVER_PLEASE_RU,
  I_DESCRIBE_RU,
  I_TYPE_RU,
  IF_ANY_COMPLAINT_RU,
  IF_THIS_DEFINITION_RU,
  IF_THIS_DEFINITIONS_RU,
  IF_WE_DECLINE_RU,
  IF_WE_TERMINATE_RU,
  IF_YOU_ADULT_RU,
  IF_YOU_CHOSEN_RU,
  IF_YOU_HAVE_QUESTION_RU,
  IF_YOU_HAVE_QUESTIONS_RU,
  IF_YOU_LOCATED_EU_RU,
  IF_YOU_LOCATED_IN_CANADA_RU,
  IF_YOU_NEED_RU,
  IF_YOU_PROVIDE_RU,
  IF_YOU_RESIDENT_OF_CALIFORNIA_RU,
  IF_YOU_RESIDENT_OF_VIRGINIA_RU,
  IF_YOU_USE_AGENT_RU,
  IF_YOU_USING_RU,
  IF_YOU_WISH_RU,
  IN_NO_EVENT_RU,
  IN_ORDER_TO_RESOLVE_RU,
  IN_SHORT_RU,
  IN_SOME_EXCEPTIONAL_CASES_RU,
  IN_SOME_REGIONS_EEA_UK_RU,
  IN_SOME_REGIONS_RU,
  IN_WHAT_SITUATIONS_RU,
  INFORMAL_NEGOTIATIONS_RU,
  INFORMATION_RU,
  J_DESCRIBE_RU,
  J_TYPE_RU,
  K_DESCRIBE_RU,
  K_TYPE_RU,
  L_TYPE_RU,
  LAST_UPDATE_RU,
  LEGAL_OBLIGATIONS_RU,
  MORE_INFO_ABOUT_RU,
  MORE_INFO_RU,
  MOST_WEB_AND_MOBILE_RU,
  MOST_WEB_RU,
  MUSIC_SAVED_RU,
  NINETEENTH_PART_OF_TERMS_RU,
  NINTH_PART_OF_TERMS_RU,
  NINTH_PART_RU,
  NO_INTERNET_RU,
  NO_USER_FEES_RU,
  OKAY_RU,
  OOPS_RU,
  OPEN_THE_APP_RU,
  OTHER_PRIVACY_RIGHTS_RU,
  OUR_CONTENT_RU,
  OUR_INTELLECTUAL_PROPERTY_RU,
  PERSONAL_DATA_MEANS_RU,
  PERSONAL_INFO_RU,
  PERSONAL_INFO_YOU_DISCLOSE_RU,
  PLEASE_REVIEW_RU,
  PRIVACY_POLICY_RU,
  QUESTION_OR_CONCERNS_RU,
  READING_THIS_NOTICE_RU,
  RIGHT_TO_APPEAL_RU,
  RIGHT_TO_BE_INFORMED_RU,
  RIGHT_TO_BE_INFORMED_WHETHER_OR_NOT_RU,
  RIGHT_TO_NON_DISCRIMINATION_RU,
  RIGHTS_TO_LIMIT_RU,
  RIGHTS_TO_REQUEST_RU,
  SALE_OF_PERSONAL_DATA_RU,
  SEARCH_RU,
  SECOND_PART_OF_TERMS_RU,
  SECOND_PART_RU,
  SENSITIVE_INFO_RU,
  SEVENTEENTH_PART_OF_TERMS_RU,
  SEVENTH_PART_OF_TERMS_RU,
  SEVENTH_PART_RU,
  SIXTEENTH_PART_OF_TERMS_RU,
  SIXTH_PART_OF_TERMS_RU,
  SIXTH_PART_RU,
  SORRY_RU,
  SUBJECT_TO_YOUR_COMPLIANCE_RU,
  SUBMISSION_RU,
  SUMMARY_OF_KEY_POINTS_RU,
  SUMMARY_PROVIDES_RU,
  SUPPLEMENTAL_RU,
  TABLE_OF_CONTENTS_RU,
  TENTH_PART_OF_TERMS_RU,
  TENTH_PART_RU,
  TERMS_AND_CONDITIONS_RU,
  THE_CONTENT_AND_MARKS_RU,
  THE_FINAL_STEP_RU,
  THE_GENERAL_DATA_PROTECTION_RU,
  THE_INFO_PROVIDED_RU,
  THE_INFO_WE_COLLECT_RU,
  THE_SERVICES_ARE_PROVIDED_RU,
  THE_SERVICES_DOES_NOT_RU,
  THE_SERVICES_RU,
  THERE_MAY_BE_INFORMATION_RU,
  THESE_LEGAL_TERMS_AND_ANY_POLICIES_RU,
  THESE_LEGAL_TERMS_GOVERNED_RU,
  THESE_LEGAL_TERMS_RU,
  THESE_LEGAL_TERMS_SHALL_RU,
  THIRD_PART_OF_TERMS_RU,
  THIRD_PART_RU,
  THIRTEENTH_PART_OF_TERMS_RU,
  THIRTEENTH_PART_RU,
  THIS_PRIVACY_NOTICE_RU,
  TO_EXPEDITE_RESOLUTION_RU,
  TO_MAY_PROCESS_RU,
  TO_SAVE_OR_PROTECT_RU,
  TOU_MAY_NOT_ACCESS_RU,
  TWELFTH_PART_OF_TERMS_RU,
  TWELFTH_PART_RU,
  TWENTIETH_ONE_PART_OF_TERMS_RU,
  TWENTIETH_PART_OF_TERMS_RU,
  TWENTIETH_TWO_PART_OF_TERMS_RU,
  UNDER_THE_VIRGINIA_RU,
  UPON_RECEIVING_RU,
  UPON_RECEIVING_YOUR_REQUEST_RU,
  USING_THE_FLIPTOK_RU,
  VERIFICATION_PROCESS_RU,
  VIDEO_SAVED_RU,
  VIRGINIA_CDPA_RU,
  VISIT_OUR_WEBSITE_RU,
  VISITING_THE_SERVICES_RU,
  VITAL_INTERESTS_RU,
  WANT_TO_LEARN_MORE_RU,
  WE_AIM_TO_PROTECT_RU,
  WE_ALLOW_ADVERTISERS_RU,
  WE_ARE_THE_OWNER_RU,
  WE_CANNOT_GUARANTEE_RU,
  WE_CARE_ABOUT_RU,
  WE_COLLECT_RU,
  WE_DO_NOT_ASSERT_RU,
  WE_DO_NOT_KNOWINGLY_RU,
  WE_DO_NOT_PROCESS_RU,
  WE_DO_NOT_PROCESS_SENSITIVE_RU,
  WE_DO_NOT_RECEIVE_RU,
  WE_HAVE_IMPLEMENTED_RU,
  WE_HAVE_NOT_COLLECTED_RU,
  WE_HAVE_ORGANIZATIONAL_RU,
  WE_KEEP_YOUR_INFO_RU,
  WE_MAY_ALSO_RU,
  WE_MAY_DISCLOSE_RU,
  WE_MAY_NEED_RU,
  WE_MAY_PROCESS_INFO_FOR_SPECIFIC_PERMISSION_RU,
  WE_MAY_PROCESS_INFO_TO_PROTECT_RU,
  WE_MAY_PROCESS_YOUR_INFO_FOR_COMPLIANCE_RU,
  WE_MAY_PROCESS_YOUR_INFO_RU,
  WE_MAY_REQUEST_RU,
  WE_MAY_SHARE_INFO_IN_SPECIFIC_SITUATIONS_RU,
  WE_MAY_SHARE_INFO_RU,
  WE_MAY_SHARE_OR_TRANSFER_INFO_RU,
  WE_MAY_UPDATE_INFO_RU,
  WE_MAY_USE_COOKIES_RU,
  WE_MAY_USE_YOUR_PERSONAL_INFO_RU,
  WE_NOT_DISCRIMINATE_RU,
  WE_ONLY_PROCESS_RU,
  WE_ONLY_USE_PERSONAL_INFO_RU,
  WE_OPERATE_RU,
  WE_PROCESS_YOUR_INFO_RU,
  WE_PROCESS_YOUR_INFO_TO_PROVIDE_RU,
  WE_PROCESS_YOUR_PERSONAL_INFO_RU,
  WE_RECOMMEND_RU,
  WE_RESERVE_ALL_RU,
  WE_RESERVE_RIGHT_RU,
  WE_RESERVE_THE_RIGHT_RU,
  WE_VALUE_YOUR_ATTENTION_RU,
  WE_WILL_CONSIDER_RU,
  WE_WILL_MAINTAIN_RU,
  WE_WILL_ONLY_KEEP_RU,
  WE_WILL_UPDATE_RU,
  WHAT_ARE_YOU_RIGHTS_RU,
  WHAT_CATEGORIES_RU,
  WHEN_WE_HAVE_NO_RU,
  WHEN_YOU_VISIT_RU,
  WILL_YOUR_MORE_INFO_RU,
  WITHDRAWING_YOUR_CONSENT_IF_WE_RU,
  WITHDRAWING_YOUR_CONSENT_RU,
  WORKING_WITH_RU,
  YOU_AGREE_TO_DEFEND_RU,
  YOU_AND_SERVICES_RU,
  YOU_ARE_RESPONSIBLE_RU,
  YOU_CAN_ASK_RU,
  YOU_CAN_CONTACT_RU,
  YOU_CAN_CONTACT_US_RU,
  YOU_MAY_CONTACT_RU,
  YOU_MAY_CONTACT_US_RU,
  YOU_MAY_OBJECT_RU,
  YOUR_RIGHTS_RU,
  YOUR_RIGHTS_WITH_RESPECT_RU,
  YOUR_SUBMISSION_RU,
  YOUR_USE_OF_OUR_SERVICES_RU,
} from './russianText';

export const strings = new LocalizedStrings({
  en: {
    download: DOWNLOAD,
    downloads: DOWNLOADS,
    search: SEARCH,
    information: INFORMATION,
    about: ABOUT,
    contacts: CONTACTS,
    privacy_policy: PRIVACY_POLICY,
    terms_and_conditions: TERMS_AND_CONDITIONS,
    download_video: DOWNLOAD_VIDEO,
    download_mp3: DOWNLOAD_MP3,
    no_internet: NO_INTERNET,
    sorry: SORRY,
    okay: OKAY,
    oops: OOPS,
    music_saved: MUSIC_SAVED,
    video_saved: VIDEO_SAVED,
    do_you_want_to_save_music: DO_YOU_WANT_TO_SAVE_MUSIC,
    do_you_want_to_save_video: DO_YOU_WANT_TO_SAVE_VIDEO,
    enter_your_link: ENTER_YOUR_LINK,

    // ABOUT STRINGS

    about_project: ABOUT_PROJECT,
    if_you_need: IF_YOU_NEED,
    how_to_use: HOW_TO_USE,
    working_with: WORKING_WITH,
    go_to_the_app: GO_TO_THE_APP,
    copy_link: COPY_LINK,
    open_the_app: OPEN_THE_APP,
    the_final_step: THE_FINAL_STEP,
    benefits: BENEFITS,
    if_you_chosen: IF_YOU_CHOSEN,
    no_user_fees: NO_USER_FEES,
    high_quality: HIGH_QUALITY,
    any_format: ANY_FORMAT,
    confidentiality: CONFIDENTIALITY,
    using_the_fliptok: USING_THE_FLIPTOK,

    // CONTACTS STRINGS

    contact_us: CONTACT_US,
    you_can_contact_us: YOU_CAN_CONTACT_US,
    email: EMAIL,
    if_you_have_questions: IF_YOU_HAVE_QUESTIONS,
    we_value_your_attention: WE_VALUE_YOUR_ATTENTION,

    // PRIVACY POLICY STRINGS

    last_update: LAST_UPDATE,
    this_privacy_notice: THIS_PRIVACY_NOTICE,
    visit_our_website: VISIT_OUR_WEBSITE,
    engage_with_us: ENGAGE_WITH_US,
    questions_or_concerns: QUESTION_OR_CONCERNS,
    reading_this_privacy_notice: READING_THIS_NOTICE,
    summary_of_key_points: SUMMARY_OF_KEY_POINTS,
    summary_provides: SUMMARY_PROVIDES,
    personal_info: PERSONAL_INFO,
    when_you_visit: WHEN_YOU_VISIT,
    do_we_process: DO_WE_PROCESS,
    we_do_not_process_sensitive: WE_DO_NOT_PROCESS_SENSITIVE,
    do_we_receive: DO_WE_RECEIVE,
    we_do_not_receive: WE_DO_NOT_RECEIVE,
    how_do_we_process_info: HOW_DO_WE_PROCESS_INFO,
    we_process_your_info: WE_PROCESS_YOUR_INFO,
    in_what_situation: IN_WHAT_SITUATIONS,
    we_may_share_info: WE_MAY_SHARE_INFO,
    how_we_keep_info: HOW_WE_KEEP_INFO,
    we_have_organizational: WE_HAVE_ORGANIZATIONAL,
    what_are_you_rights: WHAT_ARE_YOU_RIGHTS,
    depending_of_where_you: DEPENDING_ON_WHERE_YOU,
    want_to_learn_more: WANT_TO_LEARN_MORE,
    table_of_contents: TABLE_OF_CONTENTS,
    first_part: FIRST_PART,
    second_part: SECOND_PART,
    third_part: THIRD_PART,
    fourth_part: FOURTH_PART,
    fifth_part: FIFTH_PART,
    sixth_part: SIXTH_PART,
    seventh_part: SEVENTH_PART,
    eighth_part: EIGHTH_PART,
    ninth_part: NINTH_PART,
    tenth_part: TENTH_PART,
    eleventh_part: ELEVENTH_PART,
    twelfth_part: TWELFTH_PART,
    thirteenth_part: THIRTEENTH_PART,
    fourteenth_part: FOURTEENTH_PART,
    fifteenth_part: FIFTEENTH_PART,
    personal_info_you_disclose: PERSONAL_INFO_YOU_DISCLOSE,
    in_short: IN_SHORT,
    we_collect: WE_COLLECT,
    sensitive_info: SENSITIVE_INFO,
    do_we_process_sensitive_info: DO_WE_PROCESS_SENSITIVE_INFO,
    all_personal_info: ALL_PERSONAL_INFO,
    we_process_your_info_to_provide: WE_PROCESS_YOUR_INFO_TO_PROVIDE,
    we_process_your_personal_info: WE_PROCESS_YOUR_PERSONAL_INFO,
    to_save_or_protect: TO_SAVE_OR_PROTECT,
    to_may_process: TO_MAY_PROCESS,
    we_only_process: WE_ONLY_PROCESS,
    if_you_located_eu: IF_YOU_LOCATED_EU,
    the_general_data_protection: THE_GENERAL_DATA_PROTECTION,
    consent: CONSENT,
    we_may_process_your_info: WE_MAY_PROCESS_YOUR_INFO,
    legal_obligations: LEGAL_OBLIGATIONS,
    we_may_process_your_info_for_compliance: WE_MAY_PROCESS_YOUR_INFO_FOR_COMPLIANCE,
    vital_interests: VITAL_INTERESTS,
    we_may_process_info_to_protect: WE_MAY_PROCESS_INFO_TO_PROTECT,
    if_you_located_in_canada: IF_YOU_LOCATED_IN_CANADA,
    we_may_process_info_for_specific_permission: WE_MAY_PROCESS_INFO_FOR_SPECIFIC_PERMISSION,
    in_some_exceptional_cases: IN_SOME_EXCEPTIONAL_CASES,
    we_may_share_info_in_specific_situations: WE_MAY_SHARE_INFO_IN_SPECIFIC_SITUATIONS,
    we_may_need: WE_MAY_NEED,
    business_transfers: BUSINESS_TRANSFERS,
    we_may_share_or_transfer_info: WE_MAY_SHARE_OR_TRANSFER_INFO,
    we_may_use_cookies: WE_MAY_USE_COOKIES,
    we_keep_your_info: WE_KEEP_YOUR_INFO,
    we_will_only_keep: WE_WILL_ONLY_KEEP,
    when_we_have_no: WHEN_WE_HAVE_NO,
    we_aim_to_protect: WE_AIM_TO_PROTECT,
    we_have_implemented: WE_HAVE_IMPLEMENTED,
    we_do_not_knowingly: WE_DO_NOT_KNOWINGLY,
    in_some_regions: IN_SOME_REGIONS,
    in_some_regions_eea_uk: IN_SOME_REGIONS_EEA_UK,
    we_will_consider: WE_WILL_CONSIDER,
    withdrawing_your_consent_if_we: WITHDRAWING_YOUR_CONSENT_IF_WE,
    withdrawing_your_consent: WITHDRAWING_YOUR_CONSENT,
    however_please: HOWEVER_PLEASE,
    cookies_and_similar: COOKIES_AND_SIMILAR,
    most_web: MOST_WEB,
    most_web_and_mobile: MOST_WEB_AND_MOBILE,
    if_you_resident_of_california: IF_YOU_RESIDENT_OF_CALIFORNIA,
    california_civil: CALIFORNIA_CIVIL,
    if_you_adult: IF_YOU_ADULT,
    ccpa: CCPA,
    california_resident: CALIFORNIA_RESIDENT,
    every_individual: EVERY_INDIVIDUAL,
    every_individual_state: EVERY_INDIVIDUAL_STATE,
    all_other: All_OTHER,
    if_this_definitions: IF_THIS_DEFINITIONS,
    what_categories: WHAT_CATEGORIES,
    we_have_not_collected: WE_HAVE_NOT_COLLECTED,
    a_type: A_TYPE,
    a_type_describe: A_DESCRIBE,
    b_type: B_TYPE,
    b_type_describe: B_DESCRIBE,
    c_type: C_TYPE,
    c_type_describe: C_DESCRIBE,
    d_type: D_TYPE,
    d_type_describe: D_DESCRIBE,
    e_type: E_TYPE,
    e_type_describe: E_DESCRIBE,
    f_type: F_TYPE,
    f_type_describe: F_DESCRIBE,
    g_type: G_TYPE,
    g_type_describe: G_DESCRIBE,
    h_type: H_TYPE,
    h_type_describe: H_DESCRIBE,
    i_type: I_TYPE,
    i_type_describe: I_DESCRIBE,
    j_type: J_TYPE,
    j_type_describe: J_DESCRIBE,
    k_type: K_TYPE,
    k_type_describe: K_DESCRIBE,
    l_type: L_TYPE,
    we_may_also: WE_MAY_ALSO,
    how_do_we_use: HOW_DO_WE_USE,
    more_info_about: MORE_INFO_ABOUT,
    you_may_contact: YOU_MAY_CONTACT,
    if_you_use_agent: IF_YOU_USE_AGENT,
    will_your_more_info: WILL_YOUR_MORE_INFO,
    we_may_disclose: WE_MAY_DISCLOSE,
    we_may_use_your_personal_info: WE_MAY_USE_YOUR_PERSONAL_INFO,
    fliptok_has_not_disclosed: FLIPTOK_HAS_NOT_DISCLOSED,
    your_rights_with_respect: YOUR_RIGHTS_WITH_RESPECT,
    right_to_request: RIGHTS_TO_REQUEST,
    you_can_ask: YOU_CAN_ASK,
    right_to_be_informed: RIGHT_TO_BE_INFORMED,
    depending_on_the_circumstances: DEPENDING_ON_THE_CIRCUMSTANCES,
    right_to_non_discriminations: RIGHT_TO_NON_DISCRIMINATION,
    we_not_discriminate: WE_NOT_DISCRIMINATE,
    rights_to_limit: RIGHTS_TO_LIMIT,
    we_do_not_process: WE_DO_NOT_PROCESS,
    verification_process: VERIFICATION_PROCESS,
    upon_receiving: UPON_RECEIVING,
    we_only_use_personal_info: WE_ONLY_USE_PERSONAL_INFO,
    other_privacy_rights: OTHER_PRIVACY_RIGHTS,
    you_may_object: YOU_MAY_OBJECT,
    if_you_resident_of_virginia: IF_YOU_RESIDENT_OF_VIRGINIA,
    virginia_cdpa: VIRGINIA_CDPA,
    under_the_virginia: UNDER_THE_VIRGINIA,
    consumer_means: CONSUMER_MEANS,
    personal_data_means: PERSONAL_DATA_MEANS,
    sale_of_personal_data: SALE_OF_PERSONAL_DATA,
    if_this_definition: IF_THIS_DEFINITION,
    the_info_we_collect: THE_INFO_WE_COLLECT,
    your_rights: YOUR_RIGHTS,
    right_to_be_informed_whether_or_not: RIGHT_TO_BE_INFORMED_WHETHER_OR_NOT,
    exercise_your_rights: EXERCISE_YOUR_RIGHTS,
    more_info: MORE_INFO,
    your_may_contact_us: YOU_MAY_CONTACT_US,
    if_you_using: IF_YOU_USING,
    we_may_request: WE_MAY_REQUEST,
    upon_receiving_your_request: UPON_RECEIVING_YOUR_REQUEST,
    right_to_appeal: RIGHT_TO_APPEAL,
    if_we_decline: IF_WE_DECLINE,
    we_will_update: WE_WILL_UPDATE,
    we_may_update_info: WE_MAY_UPDATE_INFO,
    if_you_have_question: IF_YOU_HAVE_QUESTION,
    based_on_the_app_law: BASED_ON_THE_APP_LAW,

    // TERMS AND CONDITIONS STRING

    agreement_to_our_legal_terms: AGREEMENT_TO_OUR_LEGAL_TERMS,
    we_are_fliptok: WE_ARE_FLIPTOK,
    we_operate: WE_OPERATE,
    you_can_contact: YOU_CAN_CONTACT,
    these_legal_terms: THESE_LEGAL_TERMS,
    supplemental: SUPPLEMENTAL,
    all_users: ALL_USERS,
    we_recommend: WE_RECOMMEND,
    first_part_terms: FIRST_PART_OF_TERMS,
    second_part_terms: SECOND_PART_OF_TERMS,
    third_part_terms: THIRD_PART_OF_TERMS,
    fourth_part_terms: FOURTH_PART_OF_TERMS,
    fifth_part_terms: FIFTH_PART_OF_TERMS,
    sixth_part_terms: SIXTH_PART_OF_TERMS,
    seventh_part_terms: SEVENTH_PART_OF_TERMS,
    eighth_part_terms: EIGHTH_PART_OF_TERMS,
    ninth_part_terms: NINTH_PART_OF_TERMS,
    tenth_part_terms: TENTH_PART_OF_TERMS,
    eleventh_part_terms: ELEVENTH_PART_OF_TERMS,
    twelfth_part_terms: TWELFTH_PART_OF_TERMS,
    thirteenth_part_terms: THIRTEENTH_PART_OF_TERMS,
    fourteenth_part_terms: FOURTEENTH_PART_OF_TERMS,
    fifteenth_part_terms: FIFTEENTH_PART_OF_TERMS,
    sixteenth_part_terms: SIXTEENTH_PART_OF_TERMS,
    seventeenth_part_terms: SEVENTEENTH_PART_OF_TERMS,
    eighteenth_part_terms: EIGHTEENTH_PART_OF_TERMS,
    nineteenth_part_terms: NINETEENTH_PART_OF_TERMS,
    twentieth_part_terms: TWENTIETH_PART_OF_TERMS,
    twentieth_one_part_terms: TWENTIETH_ONE_PART_OF_TERMS,
    twentieth_two_part_terms: TWENTIETH_TWO_PART_OF_TERMS,
    the_info_provided: THE_INFO_PROVIDED,
    the_services: THE_SERVICES,
    our_intellectual_property: OUR_INTELLECTUAL_PROPERTY,
    we_are_the_owner: WE_ARE_THE_OWNER,
    our_content: OUR_CONTENT,
    the_content_and_marks: THE_CONTENT_AND_MARKS,
    your_use_of_our_services: YOUR_USE_OF_OUR_SERVICES,
    subject_to_your_compliance: SUBJECT_TO_YOUR_COMPLIANCE,
    except_and_set_out: EXCEPT_AND_SET_OUT,
    if_you_wish: IF_YOU_WISH,
    we_reserve_all: WE_RESERVE_ALL,
    any_breach: ANY_BREACH,
    your_submission: YOUR_SUBMISSION,
    please_review: PLEASE_REVIEW,
    submission: SUBMISSION,
    bu_directly: BU_DIRECTLY,
    you_are_responsible: YOU_ARE_RESPONSIBLE,
    bu_sending: BU_SENDING,
    bu_using_services: BU_USING_SERVICES,
    if_you_provide: IF_YOU_PROVIDE,
    tou_may_not_access: TOU_MAY_NOT_ACCESS,
    as_a_user_of_services: AS_A_USER_OF_SERVICES,
    the_services_does_not: THE_SERVICES_DOES_NOT,
    you_and_services: YOU_AND_SERVICES,
    bu_submitting: BY_SUBMITTING,
    we_do_not_assert: WE_DO_NOT_ASSERT,
    we_allow_advertisers: WE_ALLOW_ADVERTISERS,
    we_reserve_right: WE_RESERVE_RIGHT,
    we_care_about: WE_CARE_ABOUT,
    these_legal_terms_shall: THESE_LEGAL_TERMS_SHALL,
    if_we_terminate: IF_WE_TERMINATE,
    we_reserve_the_right: WE_RESERVE_THE_RIGHT,
    we_cannot_guarantee: WE_CANNOT_GUARANTEE,
    these_legal_terms_governed: THESE_LEGAL_TERMS_GOVERNED,
    informal_negotiations: INFORMAL_NEGOTIATIONS,
    to_expedite_resolution: TO_EXPEDITE_RESOLUTION,
    binding_arbitration: BINDING_ARBITRATION,
    any_dispute: ANY_DISPUTE,
    there_may_be_information: THERE_MAY_BE_INFORMATION,
    the_services_are_provided: THE_SERVICES_ARE_PROVIDED,
    in_not_event: IN_NO_EVENT,
    you_agree_to_defend: YOU_AGREE_TO_DEFEND,
    we_will_maintain: WE_WILL_MAINTAIN,
    visiting_the_services: VISITING_THE_SERVICES,
    if_any_complaint: IF_ANY_COMPLAINT,
    these_legal_terms_and_policies: THESE_LEGAL_TERMS_AND_ANY_POLICIES,
    in_order_to_resolve: IN_ORDER_TO_RESOLVE,
    fliptok_bottom_text: FLIPTOK_BOTTOM_TEXT,
  },
  ru: {
    download: DOWNLOAD_RU,
    downloads: DOWNLOADS_RU,
    search: SEARCH_RU,
    information: INFORMATION_RU,
    about: ABOUT_RU,
    contacts: CONTACTS_RU,
    privacy_policy: PRIVACY_POLICY_RU,
    terms_and_conditions: TERMS_AND_CONDITIONS_RU,
    download_video: DOWNLOAD_VIDEO_RU,
    download_mp3: DOWNLOAD_MP3_RU,
    no_internet: NO_INTERNET_RU,
    sorry: SORRY_RU,
    okay: OKAY_RU,
    oops: OOPS_RU,
    music_saved: MUSIC_SAVED_RU,
    video_saved: VIDEO_SAVED_RU,
    do_you_want_to_save_music: DO_YOU_WANT_TO_SAVE_MUSIC_RU,
    do_you_want_to_save_video: DO_YOU_WANT_TO_SAVE_VIDEO_RU,
    enter_your_link: ENTER_YOUR_LINK_RU,

    // ABOUT STRINGS

    about_project: ABOUT_PROJECT_RU,
    if_you_need: IF_YOU_NEED_RU,
    how_to_use: HOW_TO_USE_RU,
    working_with: WORKING_WITH_RU,
    go_to_the_app: GO_TO_THE_APP_RU,
    copy_link: COPY_LINK_RU,
    open_the_app: OPEN_THE_APP_RU,
    the_final_step: THE_FINAL_STEP_RU,
    benefits: BENEFITS_RU,
    if_you_chosen: IF_YOU_CHOSEN_RU,
    no_user_fees: NO_USER_FEES_RU,
    high_quality: HIGH_QUALITY_RU,
    any_format: ANY_FORMAT_RU,
    confidentiality: CONFIDENTIALITY_RU,
    using_the_fliptok: USING_THE_FLIPTOK_RU,

    // CONTACTS STRINGS

    contact_us: CONTACT_US_RU,
    you_can_contact_us: YOU_CAN_CONTACT_US_RU,
    email: EMAIL,
    if_you_have_questions: IF_YOU_HAVE_QUESTIONS_RU,
    we_value_your_attention: WE_VALUE_YOUR_ATTENTION_RU,

    // PRIVACY POLICY STRINGS

    last_update: LAST_UPDATE_RU,
    this_privacy_notice: THIS_PRIVACY_NOTICE_RU,
    visit_our_website: VISIT_OUR_WEBSITE_RU,
    engage_with_us: ENGAGE_WITH_US_RU,
    questions_or_concerns: QUESTION_OR_CONCERNS_RU,
    reading_this_privacy_notice: READING_THIS_NOTICE_RU,
    summary_of_key_points: SUMMARY_OF_KEY_POINTS_RU,
    summary_provides: SUMMARY_PROVIDES_RU,
    personal_info: PERSONAL_INFO_RU,
    when_you_visit: WHEN_YOU_VISIT_RU,
    do_we_process: DO_WE_PROCESS_RU,
    we_do_not_process_sensitive: WE_DO_NOT_PROCESS_SENSITIVE_RU,
    do_we_receive: DO_WE_RECEIVE_RU,
    we_do_not_receive: WE_DO_NOT_RECEIVE_RU,
    how_do_we_process_info: HOW_DO_WE_PROCESS_INFO_RU,
    we_process_your_info: WE_PROCESS_YOUR_INFO_RU,
    in_what_situation: IN_WHAT_SITUATIONS_RU,
    we_may_share_info: WE_MAY_SHARE_INFO_RU,
    how_we_keep_info: HOW_WE_KEEP_INFO_RU,
    we_have_organizational: WE_HAVE_ORGANIZATIONAL_RU,
    what_are_you_rights: WHAT_ARE_YOU_RIGHTS_RU,
    depending_of_where_you: DEPENDING_ON_WHERE_YOU_RU,
    want_to_learn_more: WANT_TO_LEARN_MORE_RU,
    table_of_contents: TABLE_OF_CONTENTS_RU,
    first_part: FIRST_PART_RU,
    second_part: SECOND_PART_RU,
    third_part: THIRD_PART_RU,
    fourth_part: FOURTH_PART_RU,
    fifth_part: FIFTH_PART_RU,
    sixth_part: SIXTH_PART_RU,
    seventh_part: SEVENTH_PART_RU,
    eighth_part: EIGHTH_PART_RU,
    ninth_part: NINTH_PART_RU,
    tenth_part: TENTH_PART_RU,
    eleventh_part: ELEVENTH_PART_RU,
    twelfth_part: TWELFTH_PART_RU,
    thirteenth_part: THIRTEENTH_PART_RU,
    fourteenth_part: FOURTEENTH_PART_RU,
    fifteenth_part: FIFTEENTH_PART_RU,
    personal_info_you_disclose: PERSONAL_INFO_YOU_DISCLOSE_RU,
    in_short: IN_SHORT_RU,
    we_collect: WE_COLLECT_RU,
    sensitive_info: SENSITIVE_INFO_RU,
    do_we_process_sensitive_info: DO_WE_PROCESS_SENSITIVE_INFO_RU,
    all_personal_info: ALL_PERSONAL_INFO_RU,
    we_process_your_info_to_provide: WE_PROCESS_YOUR_INFO_TO_PROVIDE_RU,
    we_process_your_personal_info: WE_PROCESS_YOUR_PERSONAL_INFO_RU,
    to_save_or_protect: TO_SAVE_OR_PROTECT_RU,
    to_may_process: TO_MAY_PROCESS_RU,
    we_only_process: WE_ONLY_PROCESS_RU,
    if_you_located_eu: IF_YOU_LOCATED_EU_RU,
    the_general_data_protection: THE_GENERAL_DATA_PROTECTION_RU,
    consent: CONSENT_RU,
    we_may_process_your_info: WE_MAY_PROCESS_YOUR_INFO_RU,
    legal_obligations: LEGAL_OBLIGATIONS_RU,
    we_may_process_your_info_for_compliance: WE_MAY_PROCESS_YOUR_INFO_FOR_COMPLIANCE_RU,
    vital_interests: VITAL_INTERESTS_RU,
    we_may_process_info_to_protect: WE_MAY_PROCESS_INFO_TO_PROTECT_RU,
    if_you_located_in_canada: IF_YOU_LOCATED_IN_CANADA_RU,
    we_may_process_info_for_specific_permission: WE_MAY_PROCESS_INFO_FOR_SPECIFIC_PERMISSION_RU,
    in_some_exceptional_cases: IN_SOME_EXCEPTIONAL_CASES_RU,
    we_may_share_info_in_specific_situations: WE_MAY_SHARE_INFO_IN_SPECIFIC_SITUATIONS_RU,
    we_may_need: WE_MAY_NEED_RU,
    business_transfers: BUSINESS_TRANSFERS_RU,
    we_may_share_or_transfer_info: WE_MAY_SHARE_OR_TRANSFER_INFO_RU,
    we_may_use_cookies: WE_MAY_USE_COOKIES_RU,
    we_keep_your_info: WE_KEEP_YOUR_INFO_RU,
    we_will_only_keep: WE_WILL_ONLY_KEEP_RU,
    when_we_have_no: WHEN_WE_HAVE_NO_RU,
    we_aim_to_protect: WE_AIM_TO_PROTECT_RU,
    we_have_implemented: WE_HAVE_IMPLEMENTED_RU,
    we_do_not_knowingly: WE_DO_NOT_KNOWINGLY_RU,
    in_some_regions: IN_SOME_REGIONS_RU,
    in_some_regions_eea_uk: IN_SOME_REGIONS_EEA_UK_RU,
    we_will_consider: WE_WILL_CONSIDER_RU,
    withdrawing_your_consent_if_we: WITHDRAWING_YOUR_CONSENT_IF_WE_RU,
    withdrawing_your_consent: WITHDRAWING_YOUR_CONSENT_RU,
    however_please: HOWEVER_PLEASE_RU,
    cookies_and_similar: COOKIES_AND_SIMILAR_RU,
    most_web: MOST_WEB_RU,
    most_web_and_mobile: MOST_WEB_AND_MOBILE_RU,
    if_you_resident_of_california: IF_YOU_RESIDENT_OF_CALIFORNIA_RU,
    california_civil: CALIFORNIA_CIVIL_RU,
    if_you_adult: IF_YOU_ADULT_RU,
    ccpa: CCPA_RU,
    california_resident: CALIFORNIA_RESIDENT_RU,
    every_individual: EVERY_INDIVIDUAL_RU,
    every_individual_state: EVERY_INDIVIDUAL_STATE_RU,
    all_other: All_OTHER_RU,
    if_this_definitions: IF_THIS_DEFINITIONS_RU,
    what_categories: WHAT_CATEGORIES_RU,
    we_have_not_collected: WE_HAVE_NOT_COLLECTED_RU,
    a_type: A_TYPE_RU,
    a_type_describe: A_DESCRIBE_RU,
    b_type: B_TYPE_RU,
    b_type_describe: B_DESCRIBE_RU,
    c_type: C_TYPE_RU,
    c_type_describe: C_DESCRIBE_RU,
    d_type: D_TYPE_RU,
    d_type_describe: D_DESCRIBE_RU,
    e_type: E_TYPE_RU,
    e_type_describe: E_DESCRIBE_RU,
    f_type: F_TYPE_RU,
    f_type_describe: F_DESCRIBE_RU,
    g_type: G_TYPE_RU,
    g_type_describe: G_DESCRIBE_RU,
    h_type: H_TYPE_RU,
    h_type_describe: H_DESCRIBE_RU,
    i_type: I_TYPE_RU,
    i_type_describe: I_DESCRIBE_RU,
    j_type: J_TYPE_RU,
    j_type_describe: J_DESCRIBE_RU,
    k_type: K_TYPE_RU,
    k_type_describe: K_DESCRIBE_RU,
    l_type: L_TYPE_RU,
    we_may_also: WE_MAY_ALSO_RU,
    how_do_we_use: HOW_DO_WE_USE_RU,
    more_info_about: MORE_INFO_ABOUT_RU,
    you_may_contact: YOU_MAY_CONTACT_RU,
    if_you_use_agent: IF_YOU_USE_AGENT_RU,
    will_your_more_info: WILL_YOUR_MORE_INFO_RU,
    we_may_disclose: WE_MAY_DISCLOSE_RU,
    we_may_use_your_personal_info: WE_MAY_USE_YOUR_PERSONAL_INFO_RU,
    fliptok_has_not_disclosed: FLIPTOK_HAS_NOT_DISCLOSED_RU,
    your_rights_with_respect: YOUR_RIGHTS_WITH_RESPECT_RU,
    right_to_request: RIGHTS_TO_REQUEST_RU,
    you_can_ask: YOU_CAN_ASK_RU,
    right_to_be_informed: RIGHT_TO_BE_INFORMED_RU,
    depending_on_the_circumstances: DEPENDING_ON_THE_CIRCUMSTANCES_RU,
    right_to_non_discriminations: RIGHT_TO_NON_DISCRIMINATION_RU,
    we_not_discriminate: WE_NOT_DISCRIMINATE_RU,
    rights_to_limit: RIGHTS_TO_LIMIT_RU,
    we_do_not_process: WE_DO_NOT_PROCESS_RU,
    verification_process: VERIFICATION_PROCESS_RU,
    we_only_use_personal_info: WE_ONLY_USE_PERSONAL_INFO_RU,
    upon_receiving: UPON_RECEIVING_RU,
    other_privacy_rights: OTHER_PRIVACY_RIGHTS_RU,
    you_may_object: YOU_MAY_OBJECT_RU,
    if_you_resident_of_virginia: IF_YOU_RESIDENT_OF_VIRGINIA_RU,
    virginia_cdpa: VIRGINIA_CDPA_RU,
    under_the_virginia: UNDER_THE_VIRGINIA_RU,
    consumer_means: CONSUMER_MEANS_RU,
    personal_data_means: PERSONAL_DATA_MEANS_RU,
    sale_of_personal_data: SALE_OF_PERSONAL_DATA_RU,
    if_this_definition: IF_THIS_DEFINITION_RU,
    the_info_we_collect: THE_INFO_WE_COLLECT_RU,
    your_rights: YOUR_RIGHTS_RU,
    right_to_be_informed_whether_or_not: RIGHT_TO_BE_INFORMED_WHETHER_OR_NOT_RU,
    exercise_your_rights: EXERCISE_YOUR_RIGHTS_RU,
    more_info: MORE_INFO_RU,
    your_may_contact_us: YOU_MAY_CONTACT_US_RU,
    if_you_using: IF_YOU_USING_RU,
    we_may_request: WE_MAY_REQUEST_RU,
    upon_receiving_your_request: UPON_RECEIVING_YOUR_REQUEST_RU,
    right_to_appeal: RIGHT_TO_APPEAL_RU,
    if_we_decline: IF_WE_DECLINE_RU,
    we_will_update: WE_WILL_UPDATE_RU,
    we_may_update_info: WE_MAY_UPDATE_INFO_RU,
    if_you_have_question: IF_YOU_HAVE_QUESTION_RU,
    based_on_the_app_law: BASED_ON_THE_APP_LAW_RU,

    // TERMS AND CONDITIONS STRING

    agreement_to_our_legal_terms: AGREEMENT_TO_OUR_LEGAL_TERMS_RU,
    we_operate: WE_OPERATE_RU,
    you_can_contact: YOU_CAN_CONTACT_RU,
    these_legal_terms: THESE_LEGAL_TERMS_RU,
    supplemental: SUPPLEMENTAL_RU,
    all_users: ALL_USERS_RU,
    we_recommend: WE_RECOMMEND_RU,
    first_part_terms: FIRST_PART_OF_TERMS_RU,
    second_part_terms: SECOND_PART_OF_TERMS_RU,
    third_part_terms: THIRD_PART_OF_TERMS_RU,
    fourth_part_terms: FOURTH_PART_OF_TERMS_RU,
    fifth_part_terms: FIFTH_PART_OF_TERMS_RU,
    sixth_part_terms: SIXTH_PART_OF_TERMS_RU,
    seventh_part_terms: SEVENTH_PART_OF_TERMS_RU,
    eighth_part_terms: EIGHTH_PART_OF_TERMS_RU,
    ninth_part_terms: NINTH_PART_OF_TERMS_RU,
    tenth_part_terms: TENTH_PART_OF_TERMS_RU,
    eleventh_part_terms: ELEVENTH_PART_OF_TERMS_RU,
    twelfth_part_terms: TWELFTH_PART_OF_TERMS_RU,
    thirteenth_part_terms: THIRTEENTH_PART_OF_TERMS_RU,
    fourteenth_part_terms: FOURTEENTH_PART_OF_TERMS_RU,
    fifteenth_part_terms: FIFTEENTH_PART_OF_TERMS_RU,
    sixteenth_part_terms: SIXTEENTH_PART_OF_TERMS_RU,
    seventeenth_part_terms: SEVENTEENTH_PART_OF_TERMS_RU,
    eighteenth_part_terms: EIGHTEENTH_PART_OF_TERMS_RU,
    nineteenth_part_terms: NINETEENTH_PART_OF_TERMS_RU,
    twentieth_part_terms: TWENTIETH_PART_OF_TERMS_RU,
    twentieth_one_part_terms: TWENTIETH_ONE_PART_OF_TERMS_RU,
    twentieth_two_part_terms: TWENTIETH_TWO_PART_OF_TERMS_RU,
    the_info_provided: THE_INFO_PROVIDED_RU,
    the_services: THE_SERVICES_RU,
    our_intellectual_property: OUR_INTELLECTUAL_PROPERTY_RU,
    we_are_the_owner: WE_ARE_THE_OWNER_RU,
    our_content: OUR_CONTENT_RU,
    the_content_and_marks: THE_CONTENT_AND_MARKS_RU,
    your_use_of_our_services: YOUR_USE_OF_OUR_SERVICES_RU,
    subject_to_your_compliance: SUBJECT_TO_YOUR_COMPLIANCE_RU,
    except_and_set_out: EXCEPT_AND_SET_OUT_RU,
    if_you_wish: IF_YOU_WISH_RU,
    we_reserve_all: WE_RESERVE_ALL_RU,
    any_breach: ANY_BREACH_RU,
    your_submission: YOUR_SUBMISSION_RU,
    please_review: PLEASE_REVIEW_RU,
    submission: SUBMISSION_RU,
    bu_directly: BU_DIRECTLY_RU,
    you_are_responsible: YOU_ARE_RESPONSIBLE_RU,
    bu_sending: BU_SENDING_RU,
    bu_using_services: BU_USING_SERVICES_RU,
    if_you_provide: IF_YOU_PROVIDE_RU,
    tou_may_not_access: TOU_MAY_NOT_ACCESS_RU,
    as_a_user_of_services: AS_A_USER_OF_SERVICES_RU,
    the_services_does_not: THE_SERVICES_DOES_NOT_RU,
    you_and_services: YOU_AND_SERVICES_RU,
    bu_submitting: BY_SUBMITTING_RU,
    we_do_not_assert: WE_DO_NOT_ASSERT_RU,
    we_allow_advertisers: WE_ALLOW_ADVERTISERS_RU,
    we_reserve_right: WE_RESERVE_RIGHT_RU,
    we_care_about: WE_CARE_ABOUT_RU,
    these_legal_terms_shall: THESE_LEGAL_TERMS_SHALL_RU,
    if_we_terminate: IF_WE_TERMINATE_RU,
    we_reserve_the_right: WE_RESERVE_THE_RIGHT_RU,
    we_cannot_guarantee: WE_CANNOT_GUARANTEE_RU,
    these_legal_terms_governed: THESE_LEGAL_TERMS_GOVERNED_RU,
    informal_negotiations: INFORMAL_NEGOTIATIONS_RU,
    to_expedite_resolution: TO_EXPEDITE_RESOLUTION_RU,
    binding_arbitration: BINDING_ARBITRATION_RU,
    any_dispute: ANY_DISPUTE_RU,
    there_may_be_information: THERE_MAY_BE_INFORMATION_RU,
    the_services_are_provided: THE_SERVICES_ARE_PROVIDED_RU,
    in_not_event: IN_NO_EVENT_RU,
    you_agree_to_defend: YOU_AGREE_TO_DEFEND_RU,
    we_will_maintain: WE_WILL_MAINTAIN_RU,
    visiting_the_services: VISITING_THE_SERVICES_RU,
    if_any_complaint: IF_ANY_COMPLAINT_RU,
    these_legal_terms_and_policies: THESE_LEGAL_TERMS_AND_ANY_POLICIES_RU,
    in_order_to_resolve: IN_ORDER_TO_RESOLVE_RU,
    fliptok_bottom_text: FLIPTOK_BOTTOM_TEXT,
  },
});
