import LocalizedStrings from "react-native-localization";
import {
  ABOUT,
  ABOUT_PROJECT,
  ANY_FORMAT,
  BENEFITS,
  CONFIDENTIALITY,
  CONTACT_US,
  CONTACTS,
  COPY_LINK,
  DOWNLOAD,
  DOWNLOAD_MP3,
  DOWNLOAD_VIDEO,
  EMAIL,
  GO_TO_THE_APP,
  HIGH_QUALITY,
  HOW_TO_USE,
  IF_YOU_CHOSEN,
  IF_YOU_HAVE_QUESTIONS,
  IF_YOU_NEED,
  INFORMATION,
  NO_USER_FEES,
  OPEN_THE_APP,
  PRIVACY_POLICY,
  SEARCH,
  TERMS_AND_CONDITIONS,
  THE_FINAL_STEP,
  USING_THE_FLIPTOK, WE_VALUE_YOUR_ATTENTION,
  WORKING_WITH,
  YOU_CAN_CONTACT_US
} from "./englishText";
import {
  ABOUT_PROJECT_RU,
  ABOUT_RU,
  ANY_FORMAT_RU,
  BENEFITS_RU,
  CONFIDENTIALITY_RU,
  CONTACT_US_RU,
  CONTACTS_RU,
  COPY_LINK_RU,
  DOWNLOAD_MP3_RU,
  DOWNLOAD_RU,
  DOWNLOAD_VIDEO_RU,
  GO_TO_THE_APP_RU,
  HIGH_QUALITY_RU,
  HOW_TO_USE_RU,
  IF_YOU_CHOSEN_RU,
  IF_YOU_HAVE_QUESTIONS_RU,
  IF_YOU_NEED_RU,
  INFORMATION_RU,
  NO_USER_FEES_RU,
  OPEN_THE_APP_RU,
  PRIVACY_POLICY_RU,
  SEARCH_RU,
  TERMS_AND_CONDITIONS_RU,
  THE_FINAL_STEP_RU,
  USING_THE_FLIPTOK_RU, WE_VALUE_YOUR_ATTENTION_RU,
  WORKING_WITH_RU,
  YOU_CAN_CONTACT_US_RU
} from "./russianText";

export const strings = new LocalizedStrings({
  en:{
    download: DOWNLOAD,
    search: SEARCH,
    information: INFORMATION,
    about: ABOUT,
    contacts: CONTACTS,
    privacy_policy: PRIVACY_POLICY,
    terms_and_conditions: TERMS_AND_CONDITIONS,
    download_video: DOWNLOAD_VIDEO,
    download_mp3: DOWNLOAD_MP3,
    about_project: ABOUT_PROJECT,
    if_you_need: IF_YOU_NEED,
    how_to_use: HOW_TO_USE,
    working_with: WORKING_WITH,
    go_to_the_app: GO_TO_THE_APP,
    copy_link: COPY_LINK,
    open_the_app: OPEN_THE_APP,
    the_final_step: THE_FINAL_STEP,
    benefits: BENEFITS,
    if_you_chosen: IF_YOU_CHOSEN,
    no_user_fees: NO_USER_FEES,
    high_quality: HIGH_QUALITY,
    any_format: ANY_FORMAT,
    confidentiality: CONFIDENTIALITY,
    using_the_fliptok: USING_THE_FLIPTOK,
    contact_us: CONTACT_US,
    you_can_contact_us: YOU_CAN_CONTACT_US,
    email: EMAIL,
    if_you_have_questions: IF_YOU_HAVE_QUESTIONS,
    we_value_your_attention: WE_VALUE_YOUR_ATTENTION,
  },
  ru: {
    download: DOWNLOAD_RU,
    search: SEARCH_RU,
    information: INFORMATION_RU,
    about: ABOUT_RU,
    contacts: CONTACTS_RU,
    privacy_policy: PRIVACY_POLICY_RU,
    terms_and_conditions: TERMS_AND_CONDITIONS_RU,
    download_video: DOWNLOAD_VIDEO_RU,
    download_mp3: DOWNLOAD_MP3_RU,
    about_project: ABOUT_PROJECT_RU,
    if_you_need: IF_YOU_NEED_RU,
    how_to_use: HOW_TO_USE_RU,
    working_with: WORKING_WITH_RU,
    go_to_the_app: GO_TO_THE_APP_RU,
    copy_link: COPY_LINK_RU,
    open_the_app: OPEN_THE_APP_RU,
    the_final_step: THE_FINAL_STEP_RU,
    benefits: BENEFITS_RU,
    if_you_chosen: IF_YOU_CHOSEN_RU,
    no_user_fees: NO_USER_FEES_RU,
    high_quality: HIGH_QUALITY_RU,
    any_format: ANY_FORMAT_RU,
    confidentiality: CONFIDENTIALITY_RU,
    using_the_fliptok: USING_THE_FLIPTOK_RU,
    contact_us: CONTACT_US_RU,
    you_can_contact_us: YOU_CAN_CONTACT_US_RU,
    email: EMAIL,
    if_you_have_questions: IF_YOU_HAVE_QUESTIONS_RU,
    we_value_your_attention: WE_VALUE_YOUR_ATTENTION_RU,
  }
});
